spring:
  application:
    name: dzy
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    url: jdbc:mysql://localhost:3306/ks?serverTimezone=UTC&&characterEncoding=utf8
    username: root
    password: qwer9742
server:
  port: 8080
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl